version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: |
         docker build -t mdance/bitcoind:${CIRCLE_BUILD_NUM} .
         docker tag mdance/bitcoind:${CIRCLE_BUILD_NUM} mdance/bitcoind:latest

     # deploy the image
     - run: |
         docker push mdance/bitcoind:${CIRCLE_BUILD_NUM}
         docker push mdance/bitcoind:latest
